add_newline = false

format = """\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $golang\
    $character\
    """

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

[hostname]
ssh_only = true
format = "on [$hostname](bold red) "
