HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000000
SAVEHIST=1000000

export FPATH="${HOME}/.nix-profile/share/zsh/site-functions:${FPATH}"

autoload -Uz compinit promptinit zmv up-line-or-beginning-search \
    down-line-or-beginning-search
compinit
promptinit
autoload -U +X bashcompinit && bashcompinit

setopt autocd autolist extendedglob completeinword nohup noglobdots \
    appendhistory extended_history hist_expire_dups_first \
    hist_ignore_dups hist_ignore_space hist_verify share_history \
    auto_pushd pushd_ignore_dups pushdminus correct_all prompt_subst \
    inc_append_history_time
unsetopt beep nomatch notify

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

zstyle ':completion:*' special-dirs ..
zstyle ':completion:*' completer _expand _complete _ignored _match _correct _approximate _prefix
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' glob 1
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' match-original both
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' original true
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' prompt '%F{red}Found %e errors!%f'
zstyle ':completion:*' menu select
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-compctl true
zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' list-dirs-first true
zstyle ':completion:*' cache-path ${HOME}/.cache/zsh
zstyle ':completion:*' rehash true
zstyle ':completion:*:functions' ignored-patterns '_*'

safe_source () {
    [[ -f $1 ]] && source $1
}

safe_dot () {
    [[ -f $1 ]] && \. $@
}

for file in $(command ls ${HOME}/.config/zsh/*.zsh); do source "$file"; done
